### PR TITLE
Publish ZXing library as a package for Delphinus package manager

### PR DESCRIPTION
**Pull request by Pawe1**
It's just a idea to consider.
Maybe the whole Delphinus project (https://github.com/Memnarch/Delphinus) is not so mature but I think it's just nice idea because it can work directly with GitHub (in opposite to GetIt).

Advantages:
 - easier installation
 - spreading a word about ZXing.Delphi in new places
 - allow to add ZXing.Delphi as a dependency for other Delphinus packages.

The line with keyword "Delphinus-Support" in readme is required to find repository via GitHub API.

Oh... I also cleaned up .gitignore a bit and removed some trash files

### CODE REVIEW

**Comment by Pawe1** [comment]
This feature should now work as intended 😄 

I have dropped idea of installation via packages - it would take too much work to create them.
Instead ZXing is added into global search path so user don't have to add all of these files into project manually. (as I figured out changing patches requires IDE restart)

I hope You will find this whole idea interesting and worth trying... 🙄 

Regards
PC

**Comment by Spelt** [comment]
Hi
Thanks for the efforts, I do not want to add this package manager or any other package managers add this point. The reason is that I don;t want to maintain it somehow.

When people want to update their current branch they can do that conscientiously via a normal git pull or as a submodule update.
 
I hope you understand.

Best Regards,

**Comment by Pawe1** [comment]
This was not idea about signing a contract for maintenance 😉
Also other people (for example me) could help with this so You won't have to deal with anything.

BTW - there is not too much to maintain when You dont use Delphi packages (just directory patches)
You can check some exaples how people use this and how much changes & maintenance it requires: [OmniThreadLibrary](https://github.com/gabr42/OmniThreadLibrary) / [TChromeTabs](https://github.com/norgepaul/TChromeTabs) / [mORMot](https://github.com/synopse/mORMot)

Involving package manager is just a way to make life easier because managing libraries / dependencies  in Delphi was always pain in the ass...
- reading readme files in project to find dependencies
- finding latest versions of libraries
- downloading files
- [removing installed versions]
- unpacking / installing
- [reading how to install things]
- [creating new packages]
- [adding stuff to packages]
- [changing search & browsing patches]

...and repeat this for example 5-10x
If You ever used NuGet / Paket / everything similar, You know how big difference it makes.
Also Embarcadero noticed that so they are shipping GetIt
But IMHO current GetIt sucks because it requires official / slow way

**I understand that You don't want to have extra duties.**

_Do You have something against creating 1:1 clone (not fork) of Your repository which could be published?_

Regards
P.

**Comment by Spelt** [comment]
I'm using package managers quite a lot. In VS and Delphi.  It sure can be usefull. 

For now I don't want to add this package manager or any other package managers.  Maintenance will always be some kind of an issue.  Maybe in a few months. 

You can clone it and spread it from there if you like. I have no problems with that.

**Pull request closed without merging**
