### PR TITLE
V 3.0

### PR DESCRIPTION
**Pull request by nano103**
decode logic fixed

### CODE REVIEW

**Comment by Spelt** [comment]
And it is merged and uploaded in the v3 branch.

Thanks!

2017-01-07 21:50 GMT+01:00 nano103 <notifications@github.com>:

**Comment by GuruDelphi** [comment]
@Spelt Need PDF417 support! Hope You get this message. Sorry, I am not familar with Github yet. Please contact me for a collaboration

**Comment by Spelt** [comment]
Hi 
Sure.  I can help.

**Comment by GuruDelphi** [comment]
Hallo,

thanks for your answer. Just now, i am looking for a library, supporting PFD417 reading. So, i found zxing.Delphi.
I am a Delphi professional for 20 years and have many experience in all kind of programming with delphi and a bit in C#. But no experience with decompiler like Reflector.

I am interested to expand the functionality of Zing.Delphi to support pdf417 too. I already checked the .net command line with (beta) pdf417 support. It works, but has problems with rendering a foto to find the 2d code. There will be some work but it will be possible.

Just now, i have not too much time to learn how the decompiler works. Maybe we can work together? I think it is not much work for you, to decompile the .net sources for pdf417 support, isn’t it? And i will fit the source in Delphi. What do you think about it?

Best regards
Karsten

**Comment by Spelt** [comment]
No problem. I can decompile the 
C# source to delphi.net source.

**Comment by Spelt** [comment]
I can get it for you tonight or tommorow morning.

**Comment by GuruDelphi** [comment]
That will be Great!

**Comment by Spelt** [comment]
File is attached in post below.

There was a small problem with the conversion which did not happen in the
past. Two files gave an exception on the translation:

- DecodedBitstreamParser
- PDF417HighLevelEncoder

So you need to convert those two manually.


As a side note:

- Check also for memory leaks
- Add as extensive as possible unit tests
- Use GitHub Pull request system later on when you think its done


Anyway, hope it helps !













2017-02-02 11:40 GMT+01:00 GuruDelphi <notifications@github.com>:

**Comment by Spelt** [comment]
[PDF417.zip](https://github.com/Spelt/ZXing.Delphi/files/750383/PDF417.zip)

Seems to work now.

**Comment by Spelt** [comment]
Hi

Asking myself if you have any progress?





2017-02-03 13:03 GMT+01:00 Edward Spelt <edwardspelt@gmail.com>:

**Pull request merged**
