### PR TITLE
Fixed almost all memory leaks under Win32/Win64

### PR DESCRIPTION
**Pull request by csm101**
I re-made what already did on branch Master... there were too much differences, so I did it all again.
**What is is still left to do:**
There still are memory leaks (I didn't address them yet, but they are small, compared to the ones I fixed)  caused by the TReadResult class, when it uses the  `FResultMetadata: TDictionary<TResultMetadataType, TObject>;` member variable.

Since TObjects, with old-gen compilers, are not garbage collected, it is not possible to store instance objects in that dictionary and forget about them: they will never be deallocated.
 That dictionary should become too a TDictionary<TResultMetadataType, IReadResultItem>
 where IReadResultItem should be an interface implemented by a TInterfacedObject class.

 For example TStringObject (declared in the same unit) should become a TInterfacedObject descendant and it should implement a IStringResultItem interface (extended from IReadResultItem).
**SIDE NOTE:** 
There is a worst problem with 64 bit compilation with version 3.0, I will write a proper bug report (or a pull request, if I will find a way to fix it): it seem that, when compiled under 64 bit, the BitMatrix instances (the result of the actual scanning of the source image) are "mangled", so the barcode scanning does not work (at least for qr-codes).
I added this ToString override just for debug purposes: it dumps the bitmap as plain text. I tested the contents of the bitmatrix, while scanning the same qr-code with 32 and 64 bit and I compared them with winmerge... It seems that the first 9-10 lines of the dump are identical, then the 64 bit version starts to read "garbage" for the next 30-40 lines and then it starts again reading correctly for other 9-10 lines and it goes on like that. I suspect that it might be caused by some issues with binary-shift operators. 

function TBitMatrix.ToString: string;
var r,c:integer;
begin
   for r := 0 to Fheight -1 do begin
       for c:= 0 to Fwidth-1 do begin
         if matrix[r,c]  then
           result := result + '*'
         else
           result := result + '.';
       end;
       result := result + #13#10;
   end;
end;

### CODE REVIEW

**Comment by Spelt** [comment]
You are right since 3.0 there is a bug in 64bit windows.

I also will take a look.

I merged your version and uploaded it with some house keeping.  I updated the readme and added the lib files to the unit test project so I could remove some unused files and this will allow for better searching.

Can you do a pull and work from there?

**Comment by Spelt** [comment]
I did a new push. Forgot some things.

**Comment by Spelt** [comment]
About the 64bit bug. I see some shr in the source which should not be there.  shr in .NET is not the same as in Delphi.  Tomorrow I will dig into this.  It smells like something.

**Comment by Spelt** [comment]
Hi Carlo,

The 64bit problem has been fixed by me and is uploaded to the server, everything is working fine again.  It was something that was introduced with the Datamatrix code (also a 2D code).  Cause was usage of shr instead of TMathUtils.Asr(). See for a good explanation: http://galfar.vevb.net/wp/2009/shift-right-delphi-vs-c/ http://galfar.vevb.net/wp/2009/shift-right-delphi-vs-c/

**Comment by csm101** [comment]
great!

**Pull request merged**
