### PR TITLE
Fixes in QrCode

### PR DESCRIPTION
**Pull request by kattunga**
In Win32, QrCode has lots of memory leaks because TGenericGFPoly instance are not explicitly destroyed in each function.
The best solution I found to not touch the logic was to convert TGenericGFPoly in an TInterfacedObject.

### CODE REVIEW

**Comment by Spelt** [comment]
Hi Christian,

Thanks for the patch.

I want to investigate this one a bit. What kind of tool did you use to detect these leaks and maybe you can provide me with a failing case? 

Thanks!

**Comment by kattunga** [comment]
Hi Spelt.

Memory leaks can be easily finded with FastMM4 or EurekaLog (https://www.eurekalog.com/)

This weekend I'll try to commit a demo that uses laptop webcam to scan QR codes in realtime.
After you close the demo you will be reported with hundred of memory leaks.

Checking the code I found that several parts of the library seems to be coded to target ARC compilers (like delphi for android). this memory leaks doesn't exists on ARC platforms.

**Comment by kattunga** [comment]
I added a VCL demo application to show memory leaks.
In dpr I enabled:
ReportMemoryLeaksOnShutdown := True;

So the only thing you need to do i to run application for a while scanning different kind of codes QR codes and other barcodes.

Running inside the ide in debug mode when you close application memory leaks will be reported.

screenshot at 2018-10-27 09 41 52

**Comment by kattunga** [comment]
In my fork I only have dotmatrix memory leaks, QR is fixed.

**Comment by kattunga** [comment]
By the way, could you consider to move all test apps to demo folder?.

**Comment by Spelt** [comment]
> By the way, could you consider to move all test apps to demo folder?.

Sure.

**Comment by Spelt** [comment]
Its done and your QR fix is released too. I did not want to wait.

Thanks!

Op za 27 okt. 2018 om 14:57 schreef Christian Pradelli <
notifications@github.com>:

**Pull request merged**
